language : java
jdk :
  -openjdk8

branches:
  only :
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

#CI 실행 완료 시 메일로 알람이 간다
notifications:
  email :
    recipients:
      -jayrimkim@naver.com


#에러 해결_권한 추가
before_install :
  - chmod +x gradlew